// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_tsteven6.Models;

namespace Mission06_tsteven6.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_tsteven6.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Drama/Crime",
                            Director = "Frank Darabont",
                            Edited = true,
                            Lent = "Steve",
                            Notes = "Steve loves this movie man",
                            Rating = "R",
                            Title = "Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Drama/Music",
                            Director = "Damien Chazelle",
                            Edited = true,
                            Lent = "Steve",
                            Notes = "Steve loves this movie as well man",
                            Rating = "R",
                            Title = "Whiplash",
                            Year = 2014
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Sport/Drama",
                            Director = "Frank Darabont",
                            Edited = true,
                            Lent = "Steve",
                            Notes = "Steve loves this movie a lot man",
                            Rating = "PG-13",
                            Title = "Creed",
                            Year = 2015
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
